export const actionType={
    FETCH_ARTICLE:"FETCH_ARITCLE",
    UPLOAD_ARTICLE:"UPLOAD_ARTICLE",
    DELETE_ARITCLE:"DELETE_ARTICLE",
    VEIW_ARTICLE:'VEIW_ARTICLE',
    SEARCH_ARTICLE:'SEARCH_ARTICLE'
 }